name: org.miwarre.AreaProtection
main: org.miwarre.ap.AreaProtection
version: 0.10.0
author: Maurizio M. Gavioli aka Miwarre
team: VistaMare Software
description: "Manages protection and permissions for world areas."
license: GNU General Public License ver. 3 or later
website: http://www.vistamaresoft.com
